### ISSUE TITLE
Outlook (macOS) target solution is not longer working

### ISSUE THREAD

**Issue by pri-solis** [customerio/howtotarget#40]
Outlook (macOS) is no longer being target by this line:

_:-webkit-full-screen, _::-webkit-full-page-media, _:future, :root body:not(.Singleton) .your-class-name {
  /* Replace this comment with your styles */
}

**Testing on a MacBook Pro:**
MacOS: Ventura 13.2.1 
Outlook for Mac version 16.72.3
License: Microsoft 365 Subscription
Both New Look and Legacy Outlook

**Comment by M-J-Robbins** [comment]
I'll hopefully get this updated soon.

Looks like Niven found a new target which he shared on [EmailGeeks slack](https://emailgeeks.slack.com/archives/C1Z733K1P/p1702335295896759?thread_ts=1702334399.688619&cid=C1Z733K1P)

This should hopefully work `#converted-body .your-class-name`
