### ISSUE TITLE
Do the Outlook (pre 2007) examples work?

### ISSUE THREAD

**Issue by daniel-keogh** [customerio/howtotarget#42]
Based on my understanding, MSO rendering was introduced in OL 2007, meaning `[if mso 9]` would NOT allow you to target OL 2000. That is despite every resource I've seen on MSO conditional comments (including this one) suggesting otherwise 🤔 

```html
<!--[if mso 9]>
<td>OUTLOOK 2000</td>
<![endif]-->

<!--[if mso 10]>
<td>OUTLOOK 2002</td>
<![endif]-->

<!--[if mso 11]>
<td>OUTLOOK 2003</td>
<![endif]-->
```

I found a couple of threads that would suggest the above snippets don't work?

1. "[_I've never seen `mso` work on anything before 2007.  I'd guess someone shared that info and it's been copied since_](https://emailgeeks.slack.com/archives/C1Z733K1P/p1566915265265300)"

2. "[ _`mso` rendering came in with outlook 2007. Previous versions used IE rendering so you can use `<!--[if IE]>` to get Outlook 2000-2003. Or use `<!--[if true]>` to target both groups_](https://emailgeeks.slack.com/archives/C1Z733K1P/p1563883384056500?thread_ts=1563882903.056100&cid=C1Z733K1P)"

3. "[_In theory, excluding the T-Online parsing bug, `mso` applies only on Outlook on Windows from 2007 and above_](https://emailgeeks.slack.com/archives/C1Z733K1P/p1678310878019889?thread_ts=1678308850.391899&cid=C1Z733K1P)"

4. "[_Version 9 is indeed Outlook 2000, but doesn't use Microsoft Outlook (`mso`) rendering engine. So your condition doesn't match. So to match all Outlook using Word's rendering engine, you can do `<!--[if mso]>`. To target all Outlook using Internet Explorer's rendering engine, you can do `<!--[if IE]>`. Altogether, you can do `<!--[if (mso)|(IE)]>`_](https://emailgeeks.slack.com/archives/C1Z733K1P/p1520935727000401?thread_ts=1520898944.000309&cid=C1Z733K1P)"

So my question is, should these be removed? Or alternatively, provided with a disclaimer, since this is a widely shared way of targeting these OL versions & (unless I'm missing something) it's misinformative.

**Comment by M-J-Robbins** [comment]
Good point.
There older version were built on IE so `if IE` would have worked on them. Because it's part of Microsoft Office then maybe `if mso` might work also, or maybe not. 

But I don't currently have anything old enough to test it on, also i don't think anyone is still supporting these so easiest to remove it.
