### ISSUE TITLE
iPad Targeting is also targeting iPhone 14 and 15

### ISSUE THREAD

**Issue by alexanderlandberg** [customerio/howtotarget#48]
I just discovered that the "Apple Mail (iPad)" target, is also including iPhone 14, iPhone 14 Pro Max,  iPhone 15 and iPhone 15 Pro Max.
Also it is not including iPad mini (Gen 6) (iOS 15.0)

This is tested in Litmus only.

Best,
Alex

**Comment by M-J-Robbins** [comment]
Yes this is a tricky one, because of all the different device sizes and possible resolution. I've added some notes to the description to note that this may not always be perfectly accurate.
