### ISSUE TITLE
Add iOS17 @supports(text-transform: full-width)

### ISSUE THREAD

**Issue by M-J-Robbins** [customerio/howtotarget#50]
From emailgeeks slack
https://emailgeeks.slack.com/archives/C1Z733K1P/p1702844233094529

> If you want to target iOS 17 devices only, this method seems to work in Litmus, through a new feature check:
`@supports(text-transform: full-width) { ... }`

**Comment by M-J-Robbins** [comment]
The `full-width` value has also been support in Firefox for a while so may also need something else added to it. 
https://caniuse.com/?search=text-transform%3A%20full-width

**Comment by thefunkybassist** [comment]
Good point, I think combining it with the webkit media query should exclude Firefox at least:
`@supports(text-transform: full-width) {
    @media screen and (max-width:9999px) and (-webkit-min-device-pixel-ratio: 0) {
      /* iOS 17 fallback */
      
    }
}`

**Comment by M-J-Robbins** [comment]
Merged in this PR https://github.com/customerio/howtotarget/pull/51 

I made a small tweak as it was still getting picked up by firefox, but this seemed to work ok `@supports(text-transform: full-width) and (not (-moz-appearance: none)){`
